### PR TITLE
Add Spanish language support and a few corrections on some files.

### PR DESCRIPTION
**Pull request by DavidBaug**
I add Spanish language support on index.php, also I translated the settings to Spanish.
I've fixed some language errors on intents directory files and also added some responses.

### CODE REVIEW

**Comment by richtepa** [comment]
Thank you very much. I would like to mention you, when Spanish is availabe for ActionsOnGoogle, so you might translate the user-input and answers. Is it ok?

**Comment by DavidBaug** [comment]
Sure! I'm here for any help I can bring to you ^^

**Comment by richtepa** [comment]
I'll close the pull request. (The request will count for hacktoberfest, too!)

**Comment by DavidBaug** [comment]
Oh, thank you very much!

**Pull request closed without merging**
